### ISSUE TITLE
ładowanie statystyk historycznych z liczników dwukierunkowych (instalacja PV)

### ISSUE THREAD

**Issue by paki111** [thedeemling/hass-energa-my-meter#8]
Wiem, że ładowanie danych historycznych jest ustawione paczkami po 60 dni (1440 rekordy statystyk godzinowych). Załadowałem tak wczoraj dla kilku liczników po 730 dni, czyli max co daje nam platforma mójlicznik. Dla standardowych liczników konsumenckich gdzie jest tylko energia pobrana z sieci, wszystko działa prawidłowo.

Niestety zauważyłem, że dla liczników prosumenckich (dwukierunkowych) gdzie są dwie encje statystyczne czyli energia pobrana z sieci i oddana do sieci, nie ładują się wszystkie dane dla maksymalnego okresu 730 dni. Ponawiałem przez inicjalizację ręczną oraz przez ustawianie różnych czasów aktualizacji automatycznej.

Na początku wszystko wyglądało prawidłowo. **Załadowały się dwie pierwsze paczki po 60 dni** czyli dostałem 2880 rekordów dla każdej encji. Później się okazało, że kolejne paczki już się nie ładują. Podejrzewam, że w pierwszej fazie integracja pobiera dane, bo zauważyłem jak po inicjalizacji procesor pracuje, ale dużo dłużej niż dla licznika z jedną encją i w pewnym momencie przestaje a dane nie lądują w bazie. Z pamięcią RAM jest ok, tzn. nie przepełnia się a sam HA nie natrafia na żaden błąd krytyczny.
Poniżej zrzut z bazy jak wygląda podsumowanie ilościowe statystyk ze wszystkich liczników gdzie mam pełną historię 730 dni.

![statystyki_hist_my_meter](https://github.com/user-attachments/assets/27675b63-1149-44f2-98de-1711507abee0)

To jest wycinek logów, który wydaje się najlepszy:
```log
ERROR (MainThread) [custom_components.energa_my_meter.hass_integration.energa_coordinator] Unexpected error fetching Energa My Meter data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energa_my_meter/hass_integration/energa_coordinator.py", line 42, in _async_update_data
    return await get_instance(self.hass).async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energa_my_meter/hass_integration/energa_coordinator.py", line 75, in refresh_data
    statistics[mode] = updater.gather_stats(EnergaStatsModes[mode])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energa_my_meter/hass_integration/data_updater.py", line 89, in gather_stats
    point.date_to.strftime(DEBUGGING_DATE_FORMAT)
    ^^^^^^^^^^^^^
```
Załączam jeszcze dodatkowe logi. W pierwszym widać encję energy_consumed, ale nie widać energy_produced. W drugim logu po dodaniu licznika na nowo, czyli ładowaniu danych od początku, widać `Updating the statistics data for mode ENERGY_PRODUCED`, no ale to ładowanie powtarza się tylko 2 razy i trafiamy na opisywany przeze mnie problem z kolejnymi paczkami.
[my_meter.log](https://github.com/user-attachments/files/17813116/my_meter.log)
[my_meter_.log](https://github.com/user-attachments/files/17813117/my_meter_.log)

Po restarcie HA jak ładują się wszystkie liczniki, inicjalizacja jest ponawiana do skutku i finalnie wszystko się prezentuje prawidłowo. Na licznikach dociągają się bieżące rekordy statystyk (np. po kilka sztuk od poprzedniego ładowania). No ale z wyjątkiem liczników dwukierunkowych, bo niby są zainicjowane, ale brakujące paczki danych się nie ładują. Nie generują się też statystyki dla danych aktualnych. Czy świeże dane będą pobierane dopiero po ściągnięciu całej historii?

![image](https://github.com/user-attachments/assets/0ffea8c9-4491-419a-bf81-73dea0df2b42)

## Próby dla okresy krótsze niż 730 dni
Dalej aby przyspieszyć ładowanie danych na nowo, robiłem testy tylko dla jednego z tych dwóch liczników dwukierunkowych.
- Dla krótszego okresu np. 190 dni problem nie wystąpił i załadowało się więcej niż 2 paczki. Bez problemu udało się ściągnąć komplet danych.
![image](https://github.com/user-attachments/assets/c58c6f2d-8710-488a-8e81-069cb6f8865b)

- Przy kolejnej próbie z okresem 650 dni, było dziwne zachowanie, bo załadowała się pierwsza paczka niepełna, bo 1439 rekordów dla każdej z dwóch encji. Druga paczka już nie chciała się załadować. Może właśnie ten brakujący rekord spowodował błąd `AttributeError: 'EnergaHistoricalPoint' object has no attribute 'date_to'`
```log
2024-11-19 12:00:15.856 INFO (MainThread) [custom_components.energa_my_meter.sensor] Setting up entry sensors for Energa My Meter integration {klatka 26a fotowoltaika}...
2024-11-19 12:00:15.861 INFO (DbWorker_1) [custom_components.energa_my_meter.hass_integration.energa_coordinator] Refreshing Energa data...
2024-11-19 12:00:21.869 INFO (DbWorker_1) [custom_components.energa_my_meter.hass_integration.data_updater] Updating the statistics data for mode ENERGY_CONSUMED and zones [Strefa całodobowa:]...
2024-11-19 12:00:25.857 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform energa_my_meter is taking over 10 seconds.
2024-11-19 12:00:26.493 ERROR (MainThread) [custom_components.energa_my_meter.hass_integration.energa_coordinator] Unexpected error fetching Energa My Meter data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energa_my_meter/hass_integration/energa_coordinator.py", line 42, in _async_update_data
    return await get_instance(self.hass).async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energa_my_meter/hass_integration/energa_coordinator.py", line 75, in refresh_data
    statistics[mode] = updater.gather_stats(EnergaStatsModes[mode])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energa_my_meter/hass_integration/data_updater.py", line 89, in gather_stats
    point.date_to.strftime(DEBUGGING_DATE_FORMAT)
    ^^^^^^^^^^^^^
AttributeError: 'EnergaHistoricalPoint' object has no attribute 'date_to'
```

- Przy kolejnej próbie z dodaniem licznika na nowo, skróciłem okres na 550 dni żeby wyeliminować potencjalny błąd w danych jaki wyszedł już w pierwszej paczce dla okresu 650 dni. Przy jednym z odświeżeń trafiłem na timeout ze strony platformy mójlicznik i załadowała się część paczki, po odświeżeniu chyba załadowała się kolejna część, ale ostatecznie nie poszło.

- Przy kolejnej próbie z dodaniem licznika na nowo,  skróciłem okres jeszcze bardziej, tym razem na 515, bo tak mniej więcej mi wyszło z logów i moich obliczeń, że tam gdzieś po drodze są rekordy z błędem w danych. W przeciwieństwie do poprzednich dwóch prób, tym razem pierwsza i druga paczka załadowały się kompletne i bez time outów. Załadowała się też trzecia paczka czyli jest postęp 😄 Wywaliło się w czwartej paczce.

## Podsumowanie
Te wszystkie próby i analiza dla różnych przypadków doprowadziły mnie do wniosku, że trzeba zrobić fixa na obsługę błędu w danych, może jakiś null, może to: `AttributeError: 'EnergaHistoricalPoint' object has no attribute 'date_to'`. Przypadek dotyczy prawdopodobnie tylko energii oddawanej do sieci.

**Comment by thedeemling** [comment]
Brzmi jak mój błąd w obsłudze dat w przypadku, kiedy energa zwróciła estymowany punkt historyczny:
https://github.com/thedeemling/hass-energa-my-meter/blob/main/custom_components/energa_my_meter/hass_integration/data_updater.py#L85

Z jakiegoś powodu w tym przypadku Energa nie zwraca daty (a ja używam jej tylko do wypisania informacji do debugu... więc zupełnie bez sensu w tym przypadku spowodowałem błąd ;))
https://github.com/thedeemling/hass-energa-my-meter/blob/main/custom_components/energa_my_meter/hass_integration/data_updater.py#L89

Punkty estymowane i tak są porzucane, bo nie mogę ich zaktualizować potem faktycznymi danymi.

Zastanawia mnie tylko, czemu masz estymaty w danych historycznych...? Myślałem, że Energa je zwraca tylko dla aktualnych danych. 

Dziś wieczorem poprawię ten błąd w kodzie z próbą wypisania do kodu pustej daty (żeby nie wyrzucał takimi brzydalami), ale żeby się upewnić, że algorytm działa... Czy mógłbyś:

1. Włączyć sobie logi w trybie debug
2. Zobaczyć, z jakimi parametrami odpytujemy API Energi o dane historyczne
3. Zobaczyć, czy faktycznie idą tam estymaty/podesłać plik (po depersonalizacji, oczywiście), żebym mógł przeanalizować?

**Comment by thedeemling** [comment]
Pechowo strona Energi pokazuje teraz błąd :)
![image](https://github.com/user-attachments/assets/33a27323-3a3c-44d7-a528-9badf642ca90)

więc przetestuję i wrzucę poprawkę później.

**Comment by jj641** [comment]
Warto sprawdzić na stronie Energii mojlicznik.energa-operator.pl w zakładce Wytwórca od jakiego miesiąca  i roku są przechowywane  dane.

**Comment by thedeemling** [comment]
Wypuściłem poprawkę dotyczącą logowania daty dla punktu estymaty:
https://github.com/thedeemling/hass-energa-my-meter/releases/tag/2.2.1

Prawdopodobnie nie rozwiąże Twojego problemu, bo - jak mówiłem - nie zakładałem, że mogą być estymowane wartości w starych danych (myślałem, że to tylko tam, gdzie Energa "przewiduje" wartości - np. "teraz" albo "za godzinę"). Daj znać.

Mam do Was dwa kolejne pytania:
1. Czy mogła się zdarzyć taka sytuacja, że dane produkcji energii zostały zbierane później niż konsumpcji? Np. mamy licznik, dopiero po roku zrobiliśmy z niego dwukierunkowy - czy w takiej sytuacji Energa nadaje nowy numer i część danych po prostu jest zbierana później? Założyłem w algorytmie, że one są równolegle produkowane.

2. Czy w przypadku zerowej produkcji, Energa zwraca `0` w odpowiedziach, czy puste wartości (`null`?)

**Comment by paki111** [comment]
> Warto sprawdzić na stronie Energii mojlicznik.energa-operator.pl w zakładce Wytwórca od jakiego miesiąca i roku są przechowywane rzeczywiste dane Energii **wprowadzonej** do sieci w kWh (a nie **wyprodukowanej** w instalacji fotowoltaicznej - uwagi [paki111] - Identyfikatory encji)

W zakładce "Wytwórca" też są dane trzymane 2 lata. Szkoda, bo to tylko suma miesięczna, to mogliby trzymać dłużej. Ja na szczęście już 4 lata temu sobie te miesięczne podsumowania skopiowałem.

> Wypuściłem poprawkę dotyczącą logowania daty dla punktu estymaty: https://github.com/thedeemling/hass-energa-my-meter/releases/tag/2.2.1

Zweryfikuję, może jeszcze dziś w nocy.

> Mam do Was dwa kolejne pytania:
> 
> 1. Czy mogła się zdarzyć taka sytuacja, że dane produkcji energii zostały zbierane później niż konsumpcji? Np. mamy licznik, dopiero po roku zrobiliśmy z niego dwukierunkowy - czy w takiej sytuacji Energa nadaje nowy numer i część danych po prostu jest zbierana później? Założyłem w algorytmie, że one są równolegle produkowane.
> 2. Czy w przypadku zerowej produkcji, Energa zwraca `0` w odpowiedziach, czy puste wartości (`null`?)

1. Tak jak pisałem wcześniej o identyfikatorze `meterPoint`, po wymianie licznika mamy inny numer licznika, ale ciągłość danych na meterPoint. Jak najbardziej może tak się zdarzyć, że jakiś czas można mieć sam import z sieci a później aktualizację umowy i zacząć eksport do sieci. Sama wymiana licznika musi być "przezroczysta" dla ciągłości pomiarów. Teraz pytanie @thedeemling jak to zrobić w Twojej integracji, bo przecież nie da się ponownie zainicjować tego samego wpisu aby dodać tryb dla energii oddawanej do sieci. Rozumiem, że po usunięciu wpisu, dane w bazie zostają i będziemy mogli ponownie dodać PPE i zaznaczyć tryb, tylko czy będzie kontynuacja odkładania statystyk?
2. API wysyła 0 w godzinach bez eksportu energii. Moim zdaniem mógłbyś zera pomijać aby ograniczyć ilość dodawanych rekordów. Np. teraz w listopadzie słońce jest krótko i mam eksport tylko przez 3 godziny a czasem nawet żadnego przez całą dobę.
```json
        "mainChart": [
            {
                "tm": "1728882000000",
                "tarAvg": 0.000964045174967252,
                "zones": [
                    0,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728885600000",
                "tarAvg": 0.00258550262673869,
                "zones": [
                    0.103,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728889200000",
                "tarAvg": 0.02336503507225458,
                "zones": [
                    0.412,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728892800000",
                "tarAvg": 0.0593971380466239,
                "zones": [
                    0.748,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728896400000",
                "tarAvg": 0.0991637096253774,
                "zones": [
                    1.135,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728900000000",
                "tarAvg": 0.1311963451238101,
                "zones": [
                    1.234,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728903600000",
                "tarAvg": 0.1354936629215757,
                "zones": [
                    1.722,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728907200000",
                "tarAvg": 0.1229327624546833,
                "zones": [
                    2.204,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728910800000",
                "tarAvg": 0.1141839451935508,
                "zones": [
                    1.882,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728914400000",
                "tarAvg": 0.0654212875319777,
                "zones": [
                    1.18,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728918000000",
                "tarAvg": 0.0272670586050331,
                "zones": [
                    0,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            },
            {
                "tm": "1728921600000",
                "tarAvg": 0.002594960681063212,
                "zones": [
                    0,
                    null,
                    null
                ],
                "est": false,
                "cplt": true
            }]
```

**Comment by paki111** [comment]
> Wypuściłem poprawkę dotyczącą logowania daty dla punktu estymaty: https://github.com/thedeemling/hass-energa-my-meter/releases/tag/2.2.1
> 
> Prawdopodobnie nie rozwiąże Twojego problemu, bo - jak mówiłem - nie zakładałem, że mogą być estymowane wartości w starych danych (myślałem, że to tylko tam, gdzie Energa "przewiduje" wartości - np. "teraz" albo "za godzinę"). Daj znać.

Owszem, nie rozwiązało to mojego problemu. Czy jest szansa na fixa?

Gdy nie mam załadowanej kompletnej historii to nie liczy mi się prawidłowo statystyka? Przyrosty bieżące widzę na jednej encji a historię na drugiej encji. Czy tak powinno być? To widok z tabeli statystyk gdzie widać tę nieciągłość w danych:

![image](https://github.com/user-attachments/assets/d6e9f45a-1eb3-49da-b2e8-13cdc38bbc33)

Aktualnie mam z tym problem, bo nie wyświetlę tego jako jedna seria na wykresie statystyk. Dopiero po dodaniu dwóch encji, widzę historię i aktualne przyrosty, ale przecież nie tak działają inne statystyki.

![image](https://github.com/user-attachments/assets/0b525ca1-5cf9-4b38-ac3a-a26afae8e6f2)

Jeżeli to jest konsekwencja Twojego "obejścia" na brak możliwości dodawania danych w HA z datą wsteczną, to OK, da się z tym żyć. Mam tylko pytanie, czy jak już uda się ściągnąć całą historię (fix:), to będzie inaczej wyglądać czy i tak będzie trzeba dodać na wykresie dwie encje aby widzieć komplet pomiarów z jednego liczydła (czyli z jednego trybu, w tym przypadku energia oddana do sieci).

**Comment by thedeemling** [comment]
Hej, w IT wszystko jest możliwe - ogarniemy i będzie działać najlepiej, jak się da, dopóki Energa nie poprawi API, a Hass ładowania statystyk :)

Przede wszystkim: czy moja poprawka wpłynęła na występowanie tego błędu podczas ładowania danych? Chciałem się skupić na usunięciu buga z kodu.

Ta encja `_energy_produced` to tzw. "live sensor" (https://github.com/thedeemling/hass-energa-my-meter/blob/main/custom_components/energa_my_meter/hass_integration/live_sensors.py#L29), który pobiera dane prezentowane przez Energę "na żywo" - w sensie, jak Energa zaktualizuje licznik, to go pobierze. 
![image](https://github.com/user-attachments/assets/fe6980be-21e0-4dd3-8876-882c8bd2d368)

Te dane pochodzą z prostego "daj mi wartość" i nie są historyzowane inaczej niż przez samego Home Assistanta (poprzez wykrywanie zmiany stanu). Ponieważ Energa rzadko aktualizuje te dane, to będziesz widział rzadkie słupki w historii. Traktuj te encje "live" raczej jako podsumowanie, "źródło prawdy" całości zużycia/produkcji.

Encje `_produced_strefa_X` to są encje statystyczne, ładowane z API historii w Moim Liczniku. One z kolei mają tylko przyrosty, bo Energa w tym api nie podaje sumarycznej wartości godzinowej :( Wyliczanie własnoręczne wartości sumarycznej dla statystyk byłoby problematyczne i pewnie powodowałoby trochę bugów (musiałbym zacząć od "teraz" - najnowszego odczytu i się cofać w historii do poprzednich dni, używając tego odczytu jako bazy. To by się łatwo rozjechało, jeżeli Energa zaokrągla wartosci (a robi to chyba do drugiego miejsca poprzecinku?).

Czy te słupki z energią oddaną od sieci nie pokrywają się z tym, co zwraca API Energi?

**Comment by paki111** [comment]
Twoja poprawka nie wpłynęła negatywnie na ogólne ładowanie danych na innych licznikach (jeżeli o to pytałeś?). 

Dziś dodałem licznik na nowo aby upewnić się, czy fix 2.2.1 rozwiązał też problem ładowania historii gdy wystąpi błąd `Unexpected error fetching Energa My Meter data` spowodowany prawdopodobnie przez `AttributeError: 'EnergaHistoricalPoint' object has no attribute 'date_to'`.  

Ustawiłem tryb debug dla logów i oto wynik: 
[home-assistant_2024-11-21T09-04-14.022Z.log](https://github.com/user-attachments/files/17843226/home-assistant_2024-11-21T09-04-14.022Z.log)
Niestety nie pomogło. Przy którejś paczce dane historyczne przestają się pobierać.

...
Zaokrąglenia zużycia na portalu są do trzeciej cyfry po przecinku.
Będę czekał na na późniejszy update z Twojej strony.

**Comment by paki111** [comment]
> Muszę tylko ostrzec: niestety, w najbliższych dniach będę miał mniej czasu na projekt, muszę nadgonić trochę spraw osobistych - wrócę do tematu w przyszłym tygodniu.

Cześć. Czy jest szansa na tego fixa do pobierania historycznego zużycia? Dane kasują się po dwóch latach, więc jak byś zrobił fixa w grudniu a ja bym go przetestował, to można by było pobrać komplet danych od początku 2023 roku.

**Comment by thedeemling** [comment]
Cześć,

jasne, spróbuję ogarnąć, teraz mam limitowany czas, ale oczekuję, ze to się zmieni w ciągu tygodnia/dwóch :)

Najpierw chciałbym zrozumieć, czemu ma wartości estymowane w samym środku danych historycznych - to nie powinno być tak, że te estymaty się zastąpiły prawidłowym odczytem...? Jeżeli nie i Energa po prostu zwraca takie estymaty, to pewnie musimy ustalić, jak sobie radzić w takiej sytuacji. Czy je zaakceptować? Odrzucić?

**Comment by paki111** [comment]
Tak, trzeba te wartości estymowane uwzględnić. Wydaje mi się, że one są całkiem dobrze policzone.

**Comment by thedeemling** [comment]
Przygotuję niedługo brancha i byłbym bardzo wdzięczny za testy. 

Planuję zrobić logikę w stylu "jeżeli ten punkt estymowany nie jest ostatnim zgłoszonym przez Energę, to użyj go jako prawdziwą wartość" - bo dodałem tę logikę ignorowania estymat, gdyż czasem Energa dodaje najnowsze punkty jako estymatę, a potem poprawia wartości na prawdziwe (case zgłoszony przez kogoś).

Niestety, aktualizowanie już wciągniętych danych to trochę problem ze względu na API Home Assistanta (muszę podać sumę i deltę, więc jak w środku się zmienia delta, to muszę przeliczyć nowe sumy).

**Comment by paki111** [comment]
> Niestety, aktualizowanie już wciągniętych danych to trochę problem ze względu na API Home Assistanta (muszę podać sumę i deltę, więc jak w środku się zmienia delta, to muszę przeliczyć nowe sumy), więc raz załadowane estymaty już będą musiały zostać.

tzn. będę miał usunąć liczniki i załadować historie od nowa? Robiłem to już nie raz, więc spoko, tylko się upewniam, bo nie do końca rozumiem powyższy cytat.

**Comment by thedeemling** [comment]
Nie, one powinny się kontynuować od momentu, w którym zakończyły :)
Chodziło mi, że ewentualne późniejsze podmiany z estymat na prawdziwe wartości (gdyby takie się pojawiły) byłoby znacznie trudniejsze.

**Comment by thedeemling** [comment]
W ramach MRa https://gitlab.com/home-assistant-custom-components/hass-energa-my-meter/-/merge_requests/20/diffs przygotowałem poprawkę, która załaduje punkty estymat jako prawdziwe dane - ale tylko w przypadku, kiedy nie są one najnowszymi wartościami (bo te czasem są nadpisywane, jak ktoś inny mi zgłosił :) ). Te prawdziwe wartości nie muszą być serwowane tego samego dnia, po prostu ogólnie we wskazanym zakresie.

Ja nie mam kompletnie jak tego przetestować (kiedyś sobie zrobię serwer do testowania tego API...), dlatego kod napisałem w 100% na sucho i prosiłbym Cię o sprawdzenie, czy zadziała. 

Znajduje się w tym branchu: https://github.com/thedeemling/hass-energa-my-meter/tree/feature/loading_estimated_stats

**Comment by thedeemling** [comment]
Poczekam na Twój feedback z wypuszczeniem tej poprawki :)

**Comment by thedeemling** [comment]
Zakładam, że wciąż jesteś zainteresowany tą poprawką? Niestety, bez Twojej pomocy nie dam rady oszacować, czy zadziałała ;)
Ew. jeżeli ktoś inny jest chętny potwierdzić działanie, z chęcią przyjmę taki feedback.

Wolałbym popracować nad tym, póki pamiętam, o co chodziło :D

**Comment by paki111** [comment]
Czy to o mnie mowa? Wyszła wersja ostatnio i myślałem że ktoś inny testował, byli wymienieni dwaj kontrybutorzy...

Jako, że zmieniły się nazwy encji, to u mnie większą robota, bo mam dość złożoną konfigurację i workflow oparty na tych encjach. To u mnie obejmuje mysql, influxdb oraz node-red. Najpierw sprawdzę na koncie gdzie mam tylko 1 licznik a później na drugim gdzie jest 12 liczników i ta dodatkowa konfiguracja. 

Sorry za opóźnienia.

**Comment by thedeemling** [comment]
W sensie, dla Ciebie przygotowałem osobną poprawkę, poprawiającą po prostu statystyki w https://github.com/thedeemling/hass-energa-my-meter/tree/feature/loading_estimated_stats

Ostatni release zawierał inną poprawkę,  którą udało się zweryfikować i naprawić :)

W tym branchu nie ma zmian z najnowszej wersji, więc jeżeli się nie upgradowałeś, to tym lepiej - tam nic się nie zmieni. Niestety, nie mogę tego "na ślepo" zmergować, bo nie wiem, czy będzie działać, a nie mam estymat w danych statystycznych na swoim koncie :(

BTW, zmiana nazw dotyczyła tylko encji odczytów z licznika, nie danych historycznych.

**Comment by paki111** [comment]
Ok, postaram się w krótkim czasie zweryfikować. Upgradu jeszcze nie robiłem. Sprawdzę wersję z tego linku 👍

**Comment by paki111** [comment]
Sprawdziłem na początek na koncie gdzie mam 1 licznik. Na start przywitał mnie taki dziwny "brak":

![Image](https://github.com/user-attachments/assets/fe23ec9f-bac7-4bd7-9dc0-a02c0c5c2715)

Maksymalny okres to 730 dni, ale skoro nie było tu daty pierwszego odczytu, to z ciekawości wybrałem 740 dni i przeszło. Wcześniej była walidacja i nie było można wpisać więcej dni niż jest w bazie. Tu zakładam nie było pierwszej daty, więc nie było z czym walidować. Przynajmniej dobrze, że się nie wysypało. Zacząłem wczytywać kolejne paczki danych historycznych...

Kilka paczek się wczytało, jednak w pewnym momencie się zatrzymało. Namierzyłem konkretny dzień i godzinę i tam nie ma nic szczególnego. Tzn. jest luka w odczytach, ale luki (dni bez odczytów) były już wcześniej i szło. Zatrzymało się na 17 lipca. 

![Image](https://github.com/user-attachments/assets/c111409a-4925-4871-ba34-9b70537d0172)

Tu jednak przerwa była wyjątkowo długa, bo kolejny pomiar pojawił się dopiero na koniec września 2024. Pewnie wypadło to już poza okresem wczytywanej paczki i skrypt uznaje to za koniec odczytów. Trzeba by wymuszać sprawdzanie kolejnych okresów aż do dnia dzisiejszego. To akurat jest licznik ze słabszą komunikacją i takie kilku dniowe luki w odczytach (bez estymacji) pojawiały się kilka razy. Natrafiliśmy więc na nowy kejs do obsłużenia - długi okres bez odczytów, po którym jednak w końcu pojawiają się dalsze dane.

**Comment by thedeemling** [comment]
Hm, masz rację, skrypt działa w następujący sposób:

1. Spróbuj wczytać ostatni zapisany punkt w bazie Home Assistanta jako moment startu wczytywania danych. Jeżeli go nie znalazłeś. uznaj, że to pierwsze wczytywanie i zacznij od ~2 lat wstecz.
2. Mając moment startu wczytywania danych, wczytuj dni w paczkach po 60 (https://github.com/thedeemling/hass-energa-my-meter/blob/main/custom_components/energa_my_meter/const.py#L29) dni
3. Jeżeli udało Ci się wczytać jakiś dzień z danymi, zapisz je w bazie danych - następna iteracja skryptu zacznie się od tego momentu (patrz pkt 1.) Odpalaj się co X minut (parametr integracji, domyślnie 300 minut: https://github.com/thedeemling/hass-energa-my-meter/blob/main/custom_components/energa_my_meter/const.py#L7).
4. Zakończ skrypt, jeżeli dotarłeś do dnia dzisiejszego.

Faktycznie nie przewidziałem sytuacji, w której nie żadnych danych w paczce. W takiej sytuacji algorytm nie zapisze żadnej statystyki w bazie danych, więc nie wie, że już przerobił ten fragment i przy następnym uruchomieniu ponownie spróbuje wczytać 60 dni od poprzedniej zapisanej statystyki = wpadnie w nieskończoną pętlę i co 300 minut będzie robił dokładnie to samo.
Muszę wymyślić jakiś sposób na to, wykrywać paczki danych bez żadnych dni, poinformować o tym użytkownika i omijać je przy następnym wczytywaniu.

Dam znać, jak przygotuję poprawkę. W międzyczasie zapytam, czy samo wczytywanie estymat działa już prawidłowo?

**Comment by thedeemling** [comment]
Najmocniej przepraszam za spore opóźnienie, niestety nie miałem możliwości wykonania poprawki wcześniej.
Spróbuj odświeżyć sobie kod komponentu z tego samego brancha. Dodałem commita:
https://github.com/thedeemling/hass-energa-my-meter/commit/7bce29441e8fbdcdd4fa2dc0846c73a4d7af3195

... w którym, jeżeli w całym okresie nie udało się znaleźć ani jednej statystyki, dodaję sztuczną, z wartością `0` na początku ostatniego wczytanego dnia. Dzięki temu skrypt nie powinien powtarzać raz załadowanych okresów.

Dałbyś mi znać, czy to pomogło?

Btw, z jakiegoś powodu owszem, przestało działać wyliczanie daty dla pierwszej statystyki. To mały bug, spróbuję go rozwiązać w wolnym czasie.

**Comment by paki111** [comment]
OK, działa :) Odczyty historyczne teraz pobrały się do końca.

**Comment by thedeemling** [comment]
Super! W https://gitlab.com/home-assistant-custom-components/hass-energa-my-meter/-/merge_requests/21 poprawiłem w międzyczasie algorytm wyszukania pierwszej statystyki.
W takim razie - merguję obydwie zmiany i wypuszczę nową wersję :)

**Comment by thedeemling** [comment]
Wypuszczone w ramach wersji https://github.com/thedeemling/hass-energa-my-meter/releases/tag/v2.4.0

Jeszcze raz wielkie dzięki za Twoje wsparcie związane z testowaniem tych zmian - bez Ciebie nie mógłbym ich wdrożyć :)

Zamykam zgłoszenie - śmiało zgłoś nowy błąd, jeżeli coś nie działa prawidłowo.
